name: test
on:
  workflow_dispatch:
    inputs:
      payload:
        description: 'Content of the user submission, as json string'
        required: true
        type: string

run-name: 'test'

jobs:
  run:
    runs-on: gpumode-nvidia-arc
    strategy:
      fail-fast: false
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@v3
    - name: Create input files
      shell: bash
      run: |
        PAYLOAD=$(jq '.inputs.payload' $GITHUB_EVENT_PATH)
        python3 -c $PAYLOAD
    - name: Upload training artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: run-result
        path: result.json

    - name: Upload profiling artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: profile-data
        path: profile_data/*
        retention-days: 1
